import { StyledComponentsRegistry } from "@/registries/StyledComponentsRegistry";
import "./globals.css";
import { Quicksand } from "next/font/google";
import { CustomThemeProvider } from "@/providers/CustomThemeProvider";
import GlobalStyle from "@/styles/global-styles";

const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={quicksand.className}>
        <StyledComponentsRegistry>
          <CustomThemeProvider>
            <GlobalStyle />
            {children}
          </CustomThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
